name: "AnonymousUser98's Ideas"
markdown: GFM
show_downloads: false
remote_theme: "pages-themes/primer"
github:
  is_project_page: false
plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
  - jekyll-remote-theme
repository: AnonymousUser98/ideas
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
